version: '3'

services:
  postgres:
    image: 'postgres:11.2-alpine'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - '3050:80'
