apiVersion: batch/v1
kind: Job
metadata:
  name: movie-voting-e2e-test
  labels:
    app: movie-voting
    type: e2e-test
spec:
  template:
    spec:
      containers:
        - name: movie-voting-e2e-test
          image: vsgdev/jsmovievoting_e2etest:4.0.0
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: e2e-test-envs
      restartPolicy: Never