---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-voting-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-voting
      type: db
  template:
    metadata:
      name: movie-voting-postgres
      labels:
        app: movie-voting
        type: db
    spec:
      containers:
        - name: postgres
          image: postgres:11.2-alpine
          readinessProbe:
            tcpSocket:
              port: 5432
          envFrom:
          - secretRef:
              name: postgress-secret
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pvc
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc

---
  apiVersion: v1
  kind: Service
  metadata:
    name: postgres-service
  spec:
    type: ClusterIP
    selector:
      app: movie-voting
      type: db
    ports:
      - targetPort: 5432
        port: 5432
