version: '3'

services:
  postgres:
    image: 'postgres:11.2-alpine'
    networks:
      - dev
    container_name: 'movie_voting_postgres'
    environment:
      POSTGRES_DB: movie
      POSTGRES_USER: vsdev
      POSTGRES_PASSWORD: 36%L*fq-aW!MWDjt
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ../server
      dockerfile: Dockerfile
    networks:
      - dev
    container_name: 'movie_voting_api'
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: movie
      POSTGRES_USER: vsdev
      POSTGRES_PASSWORD: 36%L*fq-aW!MWDjt
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - /app/node_modules
      - ../server:/app
    ports:
      - '5001:5000'

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    networks:
      - dev
    container_name: 'movie_voting_client'
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - /app/node_modules
      - ../client:/app
    ports:
      - '80:3000'

volumes:
  postgres_data:

networks:
  dev:
