---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-voting
      type: front-end
  template:
    metadata:
      labels:
        app: movie-voting
        type: front-end
    spec:
      containers:
        - name: movie-voting
          image: vsgdev/jsmovievoting_client:1.0.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          env:
          - name: REACT_APP_API_URL
            value: http://34.142.157.209:30500

---
apiVersion: v1
kind: Service
metadata:
  name: movie-voting-service
spec:
  type: NodePort
  selector:
    app: movie-voting
    type: front-end
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30080

